
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringint;
import org.datacontract.schemas._2004._07.servicelibrary.ArrayOfOrderDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrderService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.servicelibrary.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IOrderService {


    /**
     * 
     * @param customerName
     * @param orderRows
     */
    @WebMethod(operationName = "PlaceOrder", action = "http://tempuri.org/IOrderService/PlaceOrder")
    @RequestWrapper(localName = "PlaceOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PlaceOrder")
    @ResponseWrapper(localName = "PlaceOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PlaceOrderResponse")
    public void placeOrder(
        @WebParam(name = "customerName", targetNamespace = "http://tempuri.org/")
        String customerName,
        @WebParam(name = "orderRows", targetNamespace = "http://tempuri.org/")
        ArrayOfKeyValueOfstringint orderRows);

    /**
     * 
     * @param customerName
     * @return
     *     returns org.datacontract.schemas._2004._07.servicelibrary.ArrayOfOrderDTO
     */
    @WebMethod(operationName = "GetCustomerOrders", action = "http://tempuri.org/IOrderService/GetCustomerOrders")
    @WebResult(name = "GetCustomerOrdersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerOrders", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerOrders")
    @ResponseWrapper(localName = "GetCustomerOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerOrdersResponse")
    public ArrayOfOrderDTO getCustomerOrders(
        @WebParam(name = "customerName", targetNamespace = "http://tempuri.org/")
        String customerName);

}
