
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.servicelibrary.ArrayOfProductDTO;
import org.datacontract.schemas._2004._07.servicelibrary.Product;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IProductService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.servicelibrary.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IProductService {


    /**
     * 
     * @param product
     * @param amount
     */
    @WebMethod(operationName = "ChangeProductStock", action = "http://tempuri.org/IProductService/ChangeProductStock")
    @RequestWrapper(localName = "ChangeProductStock", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeProductStock")
    @ResponseWrapper(localName = "ChangeProductStockResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeProductStockResponse")
    public void changeProductStock(
        @WebParam(name = "product", targetNamespace = "http://tempuri.org/")
        Product product,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Integer amount);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.servicelibrary.ArrayOfProductDTO
     */
    @WebMethod(operationName = "GetProductsInStock", action = "http://tempuri.org/IProductService/GetProductsInStock")
    @WebResult(name = "GetProductsInStockResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProductsInStock", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductsInStock")
    @ResponseWrapper(localName = "GetProductsInStockResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductsInStockResponse")
    public ArrayOfProductDTO getProductsInStock();

    /**
     * 
     * @param price
     * @param name
     * @param stock
     */
    @WebMethod(action = "http://tempuri.org/IProductService/addProduct")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddProductResponse")
    public void addProduct(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "price", targetNamespace = "http://tempuri.org/")
        Double price,
        @WebParam(name = "stock", targetNamespace = "http://tempuri.org/")
        Integer stock);

}
