
package org.tempuri;

import javax.xml.ws.WebFault;
import org.datacontract.schemas._2004._07.servicelibrary.CustomerErrorMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CustomerErrorMessage", targetNamespace = "http://schemas.datacontract.org/2004/07/ServiceLibrary")
public class IStoreServiceAuthenticateCustomerErrorMessageFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CustomerErrorMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IStoreServiceAuthenticateCustomerErrorMessageFaultFaultMessage(String message, CustomerErrorMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IStoreServiceAuthenticateCustomerErrorMessageFaultFaultMessage(String message, CustomerErrorMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.datacontract.schemas._2004._07.servicelibrary.CustomerErrorMessage
     */
    public CustomerErrorMessage getFaultInfo() {
        return faultInfo;
    }

}
