
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfstringint;
import org.datacontract.schemas._2004._07.servicelibrary.ArrayOfOrderDTO;
import org.datacontract.schemas._2004._07.servicelibrary.ArrayOfProductDTO;
import org.datacontract.schemas._2004._07.servicelibrary.CustomerDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStoreService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.servicelibrary.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IStoreService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/IStoreService/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterResponse")
    public String register(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.datacontract.schemas._2004._07.servicelibrary.CustomerDTO
     */
    @WebMethod(operationName = "Authenticate", action = "http://tempuri.org/IStoreService/Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AuthenticateResponse")
    public CustomerDTO authenticate(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.servicelibrary.ArrayOfProductDTO
     */
    @WebMethod(operationName = "GetProductsInStock", action = "http://tempuri.org/IStoreService/GetProductsInStock")
    @WebResult(name = "GetProductsInStockResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProductsInStock", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductsInStock")
    @ResponseWrapper(localName = "GetProductsInStockResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductsInStockResponse")
    public ArrayOfProductDTO getProductsInStock();

    /**
     * 
     * @param price
     * @param name
     * @param stock
     */
    @WebMethod(action = "http://tempuri.org/IStoreService/addProduct")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddProductResponse")
    public void addProduct(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "price", targetNamespace = "http://tempuri.org/")
        Double price,
        @WebParam(name = "stock", targetNamespace = "http://tempuri.org/")
        Integer stock);

    /**
     * 
     * @param customerName
     * @param orderRows
     */
    @WebMethod(operationName = "PlaceOrder", action = "http://tempuri.org/IStoreService/PlaceOrder")
    @RequestWrapper(localName = "PlaceOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PlaceOrder")
    @ResponseWrapper(localName = "PlaceOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PlaceOrderResponse")
    public void placeOrder(
        @WebParam(name = "customerName", targetNamespace = "http://tempuri.org/")
        String customerName,
        @WebParam(name = "orderRows", targetNamespace = "http://tempuri.org/")
        ArrayOfKeyValueOfstringint orderRows);

    /**
     * 
     * @param customerName
     * @return
     *     returns org.datacontract.schemas._2004._07.servicelibrary.ArrayOfOrderDTO
     */
    @WebMethod(operationName = "GetCustomerOrders", action = "http://tempuri.org/IStoreService/GetCustomerOrders")
    @WebResult(name = "GetCustomerOrdersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerOrders", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerOrders")
    @ResponseWrapper(localName = "GetCustomerOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerOrdersResponse")
    public ArrayOfOrderDTO getCustomerOrders(
        @WebParam(name = "customerName", targetNamespace = "http://tempuri.org/")
        String customerName);

}
